# Generated by Django 5.1.2 on 2025-04-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSistem',
            fields=[
                ('id_admin', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=255)),
                ('email_admin', models.EmailField(max_length=255)),
                ('no_admin', models.CharField(max_length=11)),
                ('katalaluan_admin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bilangan_permohonan', models.IntegerField()),
                ('bilangan_diluluskan', models.IntegerField()),
                ('bilangan_ditolak', models.IntegerField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.adminsistem')),
            ],
        ),
        migrations.CreateModel(
            name='Pelajar',
            fields=[
                ('id_pelajar', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nama_pelajar', models.CharField(max_length=255)),
                ('email_pelajar', models.EmailField(max_length=255)),
                ('no_pelajar', models.CharField(max_length=15)),
                ('katalaluan_pelajar', models.CharField(max_length=30)),
                ('program_pelajar', models.CharField(max_length=255)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.adminsistem')),
            ],
        ),
        migrations.CreateModel(
            name='Penyelia',
            fields=[
                ('id_penyelia', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nama_penyelia', models.CharField(max_length=255)),
                ('email_penyelia', models.EmailField(max_length=255)),
                ('no_penyelia', models.CharField(max_length=15)),
                ('program_penyelia', models.CharField(max_length=255)),
                ('katalaluan_penyelia', models.CharField(max_length=255)),
                ('kepakaran_penyelia', models.CharField(max_length=255)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.adminsistem')),
            ],
        ),
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id_permohonan', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tarikh_permohonan', models.DateField()),
                ('sinopsis', models.CharField(max_length=3000)),
                ('id_pelajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.pelajar')),
                ('id_penyelia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.penyelia')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=70)),
                ('ulasan', models.CharField(max_length=3000)),
                ('tarikh_kemaskini_status', models.DateField()),
                ('id_permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.permohonan')),
            ],
        ),
    ]
