# Generated by Django 5.1.2 on 2025-04-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVFINDER', '0002_alter_pelajar_id_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyelia',
            name='id_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SVFINDER.adminsistem'),
        ),
    ]
