# Generated by Django 5.1.2 on 2025-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVFINDER', '0004_pelajar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelajar',
            name='gambar_pelajar',
            field=models.ImageField(blank=True, null=True, upload_to='pelajar/'),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='gambar_penyelia',
            field=models.ImageField(blank=True, null=True, upload_to='penyelia/'),
        ),
    ]
