# Generated by Django 5.1.2 on 2025-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVFINDER', '0005_pelajar_gambar_pelajar_penyelia_gambar_penyelia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penyelia',
            old_name='program_penyelia',
            new_name='category_penyelia',
        ),
        migrations.AddField(
            model_name='penyelia',
            name='academic_penyelia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='bilik_penyelia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penyelia',
            name='bio_penyelia',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
