# Generated by Django 5.1.2 on 2025-05-01 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVFINDER', '0006_rename_program_penyelia_penyelia_category_penyelia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan',
            name='sinopsis',
            field=models.FileField(upload_to='sinopsis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])]),
        ),
    ]
